import puppeteer from 'puppeteer-core';
import { mkdir } from 'node:fs/promises';
const CHROME = process.env.CHROME_PATH ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe';
await mkdir('.testshots', { recursive: true });
const b = await puppeteer.launch({ executablePath: CHROME, headless: false, defaultViewport: { width: 1600, height: 900 } });
const p = await b.newPage();
const errs = [], fails = [];
p.on('pageerror', e => errs.push(e.message));
p.on('console', m => { if (m.type() === 'error') errs.push(m.text()); });
p.on('response', r => { if (r.status() >= 400) fails.push(`${r.url()} HTTP ${r.status()}`); });
await p.goto('http://localhost:3100', { waitUntil: 'domcontentloaded', timeout: 60000 });
await p.waitForSelector('.title', { timeout: 60000 });
console.log('PASS  production bundle serves the start screen');
await p.evaluate(() => [...document.querySelectorAll('button')].find(x => x.textContent?.includes('New session'))?.click());
await p.waitForFunction(() => !!document.querySelector('canvas[aria-label="Minimap"]'), { timeout: 180000 });
await new Promise(r => setTimeout(r, 4000));
console.log('PASS  production build reaches playable state');
await p.screenshot({ path: '.testshots/06-production.png' });
console.log(errs.length ? `FAIL  console/page errors: ${errs.slice(0,3).join(' | ').slice(0,300)}` : 'PASS  no console or page errors');
console.log(fails.length ? `FAIL  failed requests: ${fails.slice(0,3).join(' | ')}` : 'PASS  no failed requests');
await b.close();
